import Navbar from './Navbar'
import './globals.css'
import { Karla } from 'next/font/google'
const karla = Karla({
    weight: '400',
    subsets: ['latin'],
    display: 'swap',
})

export const metadata = {
  title: 'Mark Protsyuk 🧑‍💻',
  description: 'Generated by next, designed by Mark Protsyuk',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={karla.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
